export default {
  userId: 40,
  username: 'admin',
  password: '$2a$10$sWH.qQmf/dHMURzE4kN0puBOdB7VWwcDFB2NvwpMaHYz6OFZwQGBy',
  nickname: '管理员',
  avatar: 'https://cdn.eleadmin.com/20200610/avatar.jpg',
  sex: '2',
  phone: '12345678901',
  email: 'eleadmin@eclouds.com',
  emailVerified: 0,
  realName: null,
  idCard: null,
  birthday: '2021-05-21',
  introduction: '遗其欲，则心静！',
  address: '',
  tellPre: '',
  tell: '',
  organizationId: 31,
  status: 0,
  deleted: 0,
  tenantId: 4,
  createTime: '2020-01-13 14:43:52',
  updateTime: '2023-04-10 15:08:51',
  organizationName: 'XXX公司',
  sexName: '女',
  roles: [
    {
      roleId: 10,
      roleCode: 'admin',
      roleName: '管理员',
      comments: '管理员',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-02-26 15:18:37',
      updateTime: '2020-03-21 15:15:54',
      userId: null
    }
  ],
  authorities: [
    {
      menuId: 336,
      parentId: 0,
      title: 'Dashboard',
      path: '/dashboard',
      component: null,
      menuType: 0,
      sortNumber: 0,
      permission: null,
      icon: 'IconProHomeOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:00:34',
      updateTime: '2025-01-10 13:35:07',
      children: null,
      checked: null
    },
    {
      menuId: 387,
      parentId: 364,
      title: '高级表格',
      path: '/extension/table',
      component: '/extension/table',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:55',
      updateTime: '2025-01-10 13:33:34',
      children: null,
      checked: null
    },
    {
      menuId: 301,
      parentId: 0,
      title: '系统管理',
      path: '/system',
      component: null,
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProSettingOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "系統管理", "en": "System"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-02-26 12:51:23',
      updateTime: '2025-01-10 13:35:27',
      children: null,
      checked: null
    },
    {
      menuId: 341,
      parentId: 340,
      title: '基础表单',
      path: '/form/basic',
      component: '/form/basic',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "基礎表單", "en": "Basic Form"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:03:51',
      updateTime: '2025-05-15 12:58:24',
      children: null,
      checked: null
    },
    {
      menuId: 355,
      parentId: 354,
      title: '成功页',
      path: '/result/success',
      component: '/result/success',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "成功頁", "en": "Success"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:07:40',
      updateTime: '2025-01-10 13:34:33',
      children: null,
      checked: null
    },
    {
      menuId: 358,
      parentId: 357,
      title: '403',
      path: '/exception/403',
      component: '/exception/403',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:08:47',
      updateTime: '2025-01-10 13:34:24',
      children: null,
      checked: null
    },
    {
      menuId: 318,
      parentId: 317,
      title: '查询机构',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 1,
      permission: 'sys:org:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:21',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 323,
      parentId: 322,
      title: '查询字典',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 1,
      permission: 'sys:dict:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:27',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 302,
      parentId: 301,
      title: '用户管理',
      path: '/system/user',
      component: '/system/user',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProUserOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "用戶管理", "en": "User"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-02-26 12:51:55',
      updateTime: '2025-01-10 13:35:25',
      children: null,
      checked: null
    },
    {
      menuId: 396,
      parentId: 395,
      title: '官网',
      path: '/iframe/eleadmin',
      component: 'https://www.eleadmin.com',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "官網", "en": "Website"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:12',
      updateTime: '2025-01-10 13:33:17',
      children: null,
      checked: null
    },
    {
      menuId: 345,
      parentId: 344,
      title: '基础列表',
      path: '/list/basic',
      component: '/list/basic',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "基礎清單", "en": "Basic List"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:10',
      updateTime: '2025-01-10 13:34:49',
      children: null,
      checked: null
    },
    {
      menuId: 308,
      parentId: 307,
      title: '查询角色',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 1,
      permission: 'sys:role:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-13 13:30:41',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 362,
      parentId: 361,
      title: '我的资料',
      path: '/user/profile',
      component: '/user/profile',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProUserOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "個人資料", "en": "Profile"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:09:58',
      updateTime: '2025-01-10 13:34:19',
      children: null,
      checked: null
    },
    {
      menuId: 3103,
      parentId: 3101,
      title: '男用户详情',
      path: '/list/users/details/1/:id',
      component: '/list/users/details',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 1,
      meta: '{"active": "/list/users/1", "lang": {"zh_TW": "男用戶詳情", "en": "MaleUserDetails"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2024-04-18 23:14:09',
      updateTime: '2025-01-10 13:33:07',
      children: null,
      checked: null
    },
    {
      menuId: 348,
      parentId: 347,
      title: '项目列表',
      path: '/list/card/project',
      component: '/list/card/project',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "項目清單", "en": "Project"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:06:35',
      updateTime: '2025-01-10 13:34:42',
      children: null,
      checked: null
    },
    {
      menuId: 337,
      parentId: 336,
      title: '工作台',
      path: '/dashboard/workplace',
      component: '/dashboard/workplace',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProDesktopOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "工作臺", "en": "Workplace"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:00:37',
      updateTime: '2025-01-10 13:35:06',
      children: null,
      checked: null
    },
    {
      menuId: 303,
      parentId: 302,
      title: '查询用户',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 1,
      permission: 'sys:user:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-02-26 12:52:06',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 313,
      parentId: 312,
      title: '查询菜单',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 1,
      permission: 'sys:menu:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 16:43:30',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 3101,
      parentId: 3100,
      title: '男用户',
      path: '/list/users/1',
      component: '/list/users',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "男用戶", "en": "Male Users"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2024-04-18 23:09:54',
      updateTime: '2025-01-10 13:33:09',
      children: null,
      checked: null
    },
    {
      menuId: 3104,
      parentId: 3102,
      title: '女用户详情',
      path: '/list/users/details/2/:id',
      component: '/list/users/details',
      menuType: 0,
      sortNumber: 1,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 1,
      meta: '{"active": "/list/users/2", "lang": {"zh_TW": "女用戶詳情", "en": "FemaleUserDetails"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2024-04-18 23:19:17',
      updateTime: '2025-01-10 13:33:06',
      children: null,
      checked: null
    },
    {
      menuId: 363,
      parentId: 361,
      title: '我的消息',
      path: '/user/message',
      component: '/user/message',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProMessageOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "我的消息", "en": "Message"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:03',
      updateTime: '2025-01-10 13:34:17',
      children: null,
      checked: null
    },
    {
      menuId: 366,
      parentId: 364,
      title: '高级弹窗',
      path: '/extension/modal',
      component: '/extension/modal',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:32:12',
      updateTime: '2025-01-10 13:34:14',
      children: null,
      checked: null
    },
    {
      menuId: 338,
      parentId: 336,
      title: '分析页',
      path: '/dashboard/analysis',
      component: '/dashboard/analysis',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProAnalysisOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"value": 1, "type": "warning"}}, "lang": {"zh_TW": "分析頁", "en": "Analysis"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:00:40',
      updateTime: '2025-01-10 13:35:04',
      children: null,
      checked: null
    },
    {
      menuId: 3102,
      parentId: 3100,
      title: '女用户',
      path: '/list/users/2',
      component: '/list/users',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "女用戶", "en": "Female Users"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2024-04-18 23:12:29',
      updateTime: '2025-01-10 13:33:08',
      children: null,
      checked: null
    },
    {
      menuId: 342,
      parentId: 340,
      title: '复杂表单',
      path: '/form/advanced',
      component: '/form/advanced',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "複雜表單", "en": "Advanced Form"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:03:56',
      updateTime: '2025-01-10 13:34:54',
      children: null,
      checked: null
    },
    {
      menuId: 356,
      parentId: 354,
      title: '失败页',
      path: '/result/fail',
      component: '/result/fail',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "失敗頁", "en": "Fail"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:07:41',
      updateTime: '2025-01-10 13:34:31',
      children: null,
      checked: null
    },
    {
      menuId: 359,
      parentId: 357,
      title: '404',
      path: '/exception/404',
      component: '/exception/404',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:08:49',
      updateTime: '2025-01-10 13:34:23',
      children: null,
      checked: null
    },
    {
      menuId: 388,
      parentId: 344,
      title: '左树右表',
      path: '/list/user',
      component: '/list/user',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "左樹右表", "en": "Tree List"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:15:01',
      updateTime: '2025-01-10 13:33:32',
      children: null,
      checked: null
    },
    {
      menuId: 340,
      parentId: 0,
      title: '表单页面',
      path: '/form',
      component: null,
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProFormOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"value": "New"}}, "lang": {"zh_TW": "表單頁面", "en": "Form"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:03:28',
      updateTime: '2025-01-10 13:34:56',
      children: null,
      checked: null
    },
    {
      menuId: 307,
      parentId: 301,
      title: '角色管理',
      path: '/system/role',
      component: '/system/role',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProIdcardOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "角色管理", "en": "Role"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-13 13:29:08',
      updateTime: '2025-01-10 13:35:21',
      children: null,
      checked: null
    },
    {
      menuId: 397,
      parentId: 395,
      title: '文档',
      path: '/iframe/eleadmin-doc',
      component: 'https://www.eleadmin.com/doc/eleadminplus/',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "檔案", "en": "Document"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:12',
      updateTime: '2025-01-10 13:33:16',
      children: null,
      checked: null
    },
    {
      menuId: 349,
      parentId: 347,
      title: '应用列表',
      path: '/list/card/application',
      component: '/list/card/application',
      menuType: 0,
      sortNumber: 2,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "應用清單", "en": "Application"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:06:39',
      updateTime: '2025-01-10 13:34:40',
      children: null,
      checked: null
    },
    {
      menuId: 312,
      parentId: 301,
      title: '菜单管理',
      path: '/system/menu',
      component: '/system/menu',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProAppstoreOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "選單管理", "en": "Menu"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 01:07:13',
      updateTime: '2025-01-10 13:35:18',
      children: null,
      checked: null
    },
    {
      menuId: 344,
      parentId: 0,
      title: '列表页面',
      path: '/list',
      component: null,
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProTableOutlined',
      hide: 0,
      meta: '{"props": {"hideTimeout": 450}, "lang": {"zh_TW": "清單頁面", "en": "List"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:07',
      updateTime: '2025-01-10 13:34:51',
      children: null,
      checked: null
    },
    {
      menuId: 350,
      parentId: 347,
      title: '文章列表',
      path: '/list/card/article',
      component: '/list/card/article',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "文章清單", "en": "Article"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:06:48',
      updateTime: '2025-01-10 13:34:39',
      children: null,
      checked: null
    },
    {
      menuId: 339,
      parentId: 336,
      title: '监控页',
      path: '/dashboard/monitor',
      component: '/dashboard/monitor',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProDashboardOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "監控頁", "en": "Monitor"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:03:12',
      updateTime: '2025-01-10 13:35:03',
      children: null,
      checked: null
    },
    {
      menuId: 332,
      parentId: 329,
      title: '查看记录',
      path: null,
      component: null,
      menuType: 1,
      sortNumber: 3,
      permission: 'sys:file:list',
      icon: null,
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-17 23:20:29',
      updateTime: '2023-05-24 11:59:06',
      children: null,
      checked: null
    },
    {
      menuId: 343,
      parentId: 340,
      title: '分步表单',
      path: '/form/step',
      component: '/form/step',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "分步表單", "en": "Step Form"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:04:06',
      updateTime: '2025-01-10 13:34:52',
      children: null,
      checked: null
    },
    {
      menuId: 370,
      parentId: 364,
      title: '消息提示',
      path: '/extension/message',
      component: '/extension/message',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:16:39',
      updateTime: '2025-01-10 13:34:06',
      children: null,
      checked: null
    },
    {
      menuId: 360,
      parentId: 357,
      title: '500',
      path: '/exception/500',
      component: '/exception/500',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:08:52',
      updateTime: '2025-01-10 13:34:21',
      children: null,
      checked: null
    },
    {
      menuId: 346,
      parentId: 344,
      title: '复杂列表',
      path: '/list/advanced',
      component: '/list/advanced',
      menuType: 0,
      sortNumber: 3,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "複雜清單", "en": "Advanced List"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-01-10 13:34:46',
      children: null,
      checked: null
    },
    {
      menuId: 352,
      parentId: 345,
      title: '修改用户',
      path: '/list/basic/edit/:id',
      component: '/list/basic/edit',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 1,
      meta: '{"active": "/list/basic", "lang": {"zh_TW": "編輯用戶", "en": "Edit User"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-01-10 13:34:37',
      children: null,
      checked: null
    },
    {
      menuId: 347,
      parentId: 344,
      title: '卡片列表',
      path: '/list/card',
      component: '/list/card',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"hideTimeout": 100}, "lang": {"zh_TW": "卡片清單", "en": "Card List"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:30',
      updateTime: '2025-01-10 13:34:43',
      children: null,
      checked: null
    },
    {
      menuId: 3105,
      parentId: 364,
      title: '布局组件',
      path: '/extension/layout',
      component: '/extension/layout',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2024-06-06 18:35:48',
      updateTime: '2025-01-10 13:33:04',
      children: null,
      checked: null
    },
    {
      menuId: 317,
      parentId: 301,
      title: '机构管理',
      path: '/system/organization',
      component: '/system/organization',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProCityOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "機构管理", "en": "Organization"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:20',
      updateTime: '2025-01-10 13:35:17',
      children: null,
      checked: null
    },
    {
      menuId: 353,
      parentId: 340,
      title: '表单构建',
      path: '/form/build',
      component: '/form/build',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}, "lang": {"zh_TW": "表單構建", "en": "Form Build"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-01-10 13:34:35',
      children: null,
      checked: null
    },
    {
      menuId: 354,
      parentId: 0,
      title: '结果页面',
      path: '/result',
      component: null,
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProCheckCircleOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "結果頁面", "en": "Result"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:07:33',
      updateTime: '2025-01-10 13:34:34',
      children: null,
      checked: null
    },
    {
      menuId: 351,
      parentId: 345,
      title: '添加用户',
      path: '/list/basic/add',
      component: '/list/basic/add',
      menuType: 0,
      sortNumber: 4,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 1,
      meta: '{"active": "/list/basic", "lang": {"zh_TW": "添加用戶", "en": "Add User"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-01-10 13:34:38',
      children: null,
      checked: null
    },
    {
      menuId: 333,
      parentId: 302,
      title: '用户详情',
      path: '/system/user/details/:id',
      component: '/system/user/details',
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProUserOutlined',
      hide: 1,
      meta: '{"active": "/system/user", "lang": {"zh_TW": "用戶詳情", "en": "UserDetails"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-05-21 11:07:54',
      updateTime: '2025-01-10 13:35:09',
      children: null,
      checked: null
    },
    {
      menuId: 3108,
      parentId: 340,
      title: '列表构建',
      path: '/list/build',
      component: '/list/build',
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}, "lang": {"zh_TW": "列表構建", "en": "List Build"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:10',
      updateTime: '2025-05-29 09:08:11',
      children: null,
      checked: null
    },
    {
      menuId: 376,
      parentId: 364,
      title: '下拉表格',
      path: '/extension/table-select',
      component: '/extension/table-select',
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:45',
      updateTime: '2025-01-10 13:33:56',
      children: null,
      checked: null
    },
    {
      menuId: 3100,
      parentId: 344,
      title: '复杂路由',
      path: '/list/users',
      component: null,
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"hideTimeout": 100}, "lang": {"zh_TW": "複雜路由", "en": "Route Demo"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2023-06-28 17:49:49',
      updateTime: '2025-01-10 13:33:11',
      children: null,
      checked: null
    },
    {
      menuId: 322,
      parentId: 301,
      title: '字典管理',
      path: '/system/dictionary',
      component: '/system/dictionary',
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProBookOutlined',
      hide: 0,
      meta: '{"hideFooter":true, "lang": {"zh_TW": "字典管理", "en": "Dictionary"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:26',
      updateTime: '2025-01-10 13:35:14',
      children: null,
      checked: null
    },
    {
      menuId: 357,
      parentId: 0,
      title: '异常页面',
      path: '/exception',
      component: null,
      menuType: 0,
      sortNumber: 5,
      permission: null,
      icon: 'IconProWarningOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "异常頁面", "en": "Exception"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:08:44',
      updateTime: '2025-01-10 13:34:26',
      children: null,
      checked: null
    },
    {
      menuId: 329,
      parentId: 301,
      title: '文件管理',
      path: '/system/file',
      component: '/system/file',
      menuType: 0,
      sortNumber: 6,
      permission: null,
      icon: 'IconProFolderOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "檔案管理", "en": "File"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-17 23:19:43',
      updateTime: '2025-01-10 13:35:10',
      children: null,
      checked: null
    },
    {
      menuId: 361,
      parentId: 0,
      title: '个人中心',
      path: '/user',
      component: null,
      menuType: 0,
      sortNumber: 6,
      permission: null,
      icon: 'IconProControlOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "個人中心", "en": "User"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:09:54',
      updateTime: '2025-01-10 13:34:20',
      children: null,
      checked: null
    },
    {
      menuId: 374,
      parentId: 364,
      title: '下拉树',
      path: '/extension/tree-select',
      component: '/extension/tree-select',
      menuType: 0,
      sortNumber: 6,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:29:03',
      updateTime: '2025-01-10 13:33:59',
      children: null,
      checked: null
    },
    {
      menuId: 327,
      parentId: 301,
      title: '登录日志',
      path: '/system/login-record',
      component: '/system/login-record',
      menuType: 0,
      sortNumber: 7,
      permission: 'sys:login-record:list',
      icon: 'IconProCalendarOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "登入日誌", "en": "LoginRecord"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:33',
      updateTime: '2025-01-10 13:35:13',
      children: null,
      checked: null
    },
    {
      menuId: 364,
      parentId: 0,
      title: '扩展组件',
      path: '/extension',
      component: null,
      menuType: 0,
      sortNumber: 7,
      permission: null,
      icon: 'IconProAppstoreAddOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:52',
      updateTime: '2025-01-10 13:34:16',
      children: null,
      checked: null
    },
    {
      menuId: 368,
      parentId: 364,
      title: '文件上传',
      path: '/extension/upload',
      component: '/extension/upload',
      menuType: 0,
      sortNumber: 7,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:58',
      updateTime: '2025-01-10 13:34:08',
      children: null,
      checked: null
    },
    {
      menuId: 395,
      parentId: 0,
      title: '内嵌页面',
      path: '/iframe',
      component: null,
      menuType: 0,
      sortNumber: 8,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "內嵌頁面", "en": "IFrame"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:20:35',
      updateTime: '2025-01-10 13:33:18',
      children: null,
      checked: null
    },
    {
      menuId: 328,
      parentId: 301,
      title: '操作日志',
      path: '/system/operation-record',
      component: '/system/operation-record',
      menuType: 0,
      sortNumber: 8,
      permission: 'sys:operation-record:list',
      icon: 'IconProLogOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "操作日誌", "en": "OperationRecord"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2020-03-21 18:24:34',
      updateTime: '2025-01-10 13:35:12',
      children: null,
      checked: null
    },
    {
      menuId: 385,
      parentId: 364,
      title: '图标选择',
      path: '/extension/icon',
      component: '/extension/icon',
      menuType: 0,
      sortNumber: 8,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:18:35',
      updateTime: '2025-01-10 13:33:36',
      children: null,
      checked: null
    },
    {
      menuId: 398,
      parentId: 0,
      title: '功能演示',
      path: '/example',
      component: '/example',
      menuType: 0,
      sortNumber: 9,
      permission: null,
      icon: 'IconProCompassOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "功能演示", "en": "Demo"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:12',
      updateTime: '2025-01-23 16:08:02',
      children: null,
      checked: null
    },
    {
      menuId: 367,
      parentId: 364,
      title: '文件列表',
      path: '/extension/file',
      component: '/extension/file',
      menuType: 0,
      sortNumber: 9,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:58',
      updateTime: '2025-01-10 13:34:09',
      children: null,
      checked: null
    },
    {
      menuId: 377,
      parentId: 364,
      title: '分割面板',
      path: '/extension/split',
      component: '/extension/split',
      menuType: 0,
      sortNumber: 10,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:45',
      updateTime: '2025-01-10 13:33:52',
      children: null,
      checked: null
    },
    {
      menuId: 399,
      parentId: 0,
      title: '获取授权',
      path: 'https://eleadmin.com/goods/26',
      component: null,
      menuType: 0,
      sortNumber: 10,
      permission: null,
      icon: 'IconProProtectOutlined',
      hide: 0,
      meta: '{"lang": {"zh_TW": "獲取授權", "en": "Authorization"}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:15:18',
      updateTime: '2025-06-18 15:49:11',
      children: null,
      checked: null
    },
    {
      menuId: 372,
      parentId: 364,
      title: '打印组件',
      path: '/extension/printer',
      component: '/extension/printer',
      menuType: 0,
      sortNumber: 11,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:11:00',
      updateTime: '2025-01-10 13:34:03',
      children: null,
      checked: null
    },
    {
      menuId: 386,
      parentId: 364,
      title: '文本组件',
      path: '/extension/text',
      component: '/extension/text',
      menuType: 0,
      sortNumber: 12,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:10:55',
      updateTime: '2025-01-10 13:33:35',
      children: null,
      checked: null
    },
    {
      menuId: 365,
      parentId: 364,
      title: '标签输入',
      path: '/extension/tag',
      component: '/extension/tag',
      menuType: 0,
      sortNumber: 13,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:13:35',
      updateTime: '2025-01-10 13:34:15',
      children: null,
      checked: null
    },
    {
      menuId: 384,
      parentId: 364,
      title: '头像组合',
      path: '/extension/avatar',
      component: '/extension/avatar',
      menuType: 0,
      sortNumber: 14,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:14:28',
      updateTime: '2025-01-10 13:33:39',
      children: null,
      checked: null
    },
    {
      menuId: 393,
      parentId: 364,
      title: '引导组件',
      path: '/extension/tour',
      component: '/extension/tour',
      menuType: 0,
      sortNumber: 15,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:15:11',
      updateTime: '2025-01-10 13:33:22',
      children: null,
      checked: null
    },
    {
      menuId: 391,
      parentId: 364,
      title: '导航菜单',
      path: '/extension/menu',
      component: '/extension/menu',
      menuType: 0,
      sortNumber: 16,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-05-21 11:11:57',
      updateTime: '2025-01-10 13:33:27',
      children: null,
      checked: null
    },
    {
      menuId: 375,
      parentId: 364,
      title: '可选卡片',
      path: '/extension/check-card',
      component: '/extension/check-card',
      menuType: 0,
      sortNumber: 17,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:45',
      updateTime: '2025-01-10 13:33:57',
      children: null,
      checked: null
    },
    {
      menuId: 392,
      parentId: 364,
      title: '水印组件',
      path: '/extension/watermark',
      component: '/extension/watermark',
      menuType: 0,
      sortNumber: 18,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-05-21 11:11:57',
      updateTime: '2025-01-10 13:33:24',
      children: null,
      checked: null
    },
    {
      menuId: 3107,
      parentId: 364,
      title: '查看器',
      path: '/extension/viewer',
      component: '/extension/viewer',
      menuType: 0,
      sortNumber: 19,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-03-07 21:59:21',
      children: null,
      checked: null
    },
    {
      menuId: 390,
      parentId: 364,
      title: '步骤条',
      path: '/extension/steps',
      component: '/extension/steps',
      menuType: 0,
      sortNumber: 19,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: '{"props": {"badge": {"isDot": true}}}',
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:05:26',
      updateTime: '2025-03-07 21:59:04',
      children: null,
      checked: null
    },
    {
      menuId: 394,
      parentId: 364,
      title: '分段器',
      path: '/extension/segmented',
      component: '/extension/segmented',
      menuType: 0,
      sortNumber: 20,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:15:03',
      updateTime: '2025-01-10 13:33:20',
      children: null,
      checked: null
    },
    {
      menuId: 389,
      parentId: 364,
      title: '标签页',
      path: '/extension/tabs',
      component: '/extension/tabs',
      menuType: 0,
      sortNumber: 21,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-06 22:26:55',
      updateTime: '2025-01-10 13:33:31',
      children: null,
      checked: null
    },
    {
      menuId: 380,
      parentId: 364,
      title: '二维码',
      path: '/extension/qr-code',
      component: '/extension/qr-code',
      menuType: 0,
      sortNumber: 22,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:29:56',
      updateTime: '2025-01-10 13:33:46',
      children: null,
      checked: null
    },
    {
      menuId: 381,
      parentId: 364,
      title: '条形码',
      path: '/extension/bar-code',
      component: '/extension/bar-code',
      menuType: 0,
      sortNumber: 23,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:29:56',
      updateTime: '2025-01-10 13:33:45',
      children: null,
      checked: null
    },
    {
      menuId: 371,
      parentId: 364,
      title: '城市选择',
      path: '/extension/regions',
      component: '/extension/regions',
      menuType: 0,
      sortNumber: 24,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-05 11:25:15',
      updateTime: '2025-01-10 13:34:04',
      children: null,
      checked: null
    },
    {
      menuId: 373,
      parentId: 364,
      title: '导入导出',
      path: '/extension/excel',
      component: '/extension/excel',
      menuType: 0,
      sortNumber: 25,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:11:03',
      updateTime: '2025-01-10 13:34:00',
      children: null,
      checked: null
    },
    {
      menuId: 369,
      parentId: 364,
      title: '拖拽排序',
      path: '/extension/dragsort',
      component: '/extension/dragsort',
      menuType: 0,
      sortNumber: 26,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:11:48',
      updateTime: '2025-01-10 13:34:07',
      children: null,
      checked: null
    },
    {
      menuId: 379,
      parentId: 364,
      title: '地图组件',
      path: '/extension/map',
      component: '/extension/map',
      menuType: 0,
      sortNumber: 27,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:11:49',
      updateTime: '2025-01-10 13:33:49',
      children: null,
      checked: null
    },
    {
      menuId: 378,
      parentId: 364,
      title: '视频播放',
      path: '/extension/player',
      component: '/extension/player',
      menuType: 0,
      sortNumber: 28,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:13:49',
      updateTime: '2025-01-10 13:33:51',
      children: null,
      checked: null
    },
    {
      menuId: 382,
      parentId: 364,
      title: '富文本框',
      path: '/extension/editor',
      component: '/extension/editor',
      menuType: 0,
      sortNumber: 29,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-02-02 20:13:57',
      updateTime: '2025-01-10 13:33:43',
      children: null,
      checked: null
    },
    {
      menuId: 383,
      parentId: 364,
      title: 'markdown',
      path: '/extension/markdown',
      component: '/extension/markdown',
      menuType: 0,
      sortNumber: 30,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2021-10-10 16:21:45',
      updateTime: '2025-01-10 13:33:41',
      children: null,
      checked: null
    },
    {
      menuId: 3106,
      parentId: 364,
      title: '代码编辑',
      path: '/extension/monaco',
      component: '/extension/monaco',
      menuType: 0,
      sortNumber: 31,
      permission: null,
      icon: 'IconProLinkOutlined',
      hide: 0,
      meta: null,
      deleted: 0,
      tenantId: 4,
      createTime: '2024-07-12 18:50:17',
      updateTime: '2025-01-10 13:33:03',
      children: null,
      checked: null
    }
  ],
  enabled: true,
  accountNonLocked: true,
  credentialsNonExpired: true,
  accountNonExpired: true
};
