onework:
  info:
    base-package: com.onework.boot
  scrape:
    cde-all-project:
      url: http://www.chinadrugtrials.org.cn/clinicaltrials.searchlist.dhtml
      incognito: false
      open-window: false
      driver-type: chrome
      thread-count: 10
      save-path: D:\药物临床试验登记与信息公示平台
    cde-project:
      url: http://www.chinadrugtrials.org.cn/clinicaltrials.searchlist.dhtml
      driver-type: chrome
      thread-count: 10
      incognito: false
      open-window: true
      save-path: D:\药物临床试验登记与信息公示平台
      max-page: 50
    cde-project-file:
      driver-type: chrome
      incognito: false
      open-window: true
      thread-count: 5
      url: http://www.chinadrugtrials.org.cn/clinicaltrials.searchlist.dhtml
      save-path: D:\药物临床试验登记与信息公示平台
    cde-project-file-parse:
      save-path: D:\药物临床试验登记与信息公示平台
      thread-count: 20
    cde-analysis:
      thread-count: 50
    ctmds-drug:
      thread-count: 50
      url: https://beian.cfdi.org.cn/CTMDS/pub/PUB010100.do?method=handle06&pageSize=10000
      file-url: https://beian.cfdi.org.cn/CTMDS/pub/PUB010100.do?method=handle07&compId=%s
      save-path: D:\药物和医疗器械临床试验机构备案系统
    ctmds-drug-file:
      save-path: D:\药物和医疗器械临床试验机构备案系统
      thread-count: 50
    ctmds-instrument:
      thread-count: 50
      url: https://beian.cfdi.org.cn/CTMDS/pub/PUB010100.do?method=handle05&pageSize=10000
      file-url: https://beian.cfdi.org.cn/CTMDS/pub/PUB010100.do?method=handle04&compId=%s
      save-path: D:\药物和医疗器械临床试验机构备案系统
    ctmds-instrument-file:
      save-path: D:\药物和医疗器械临床试验机构备案系统
      thread-count: 50
    bohe-company:
      driver-type: chrome
      incognito: false
      open-window: true
      thread-count: 5
      url: https://yao.bohe.cn/company/
      page-url: https://yao.bohe.cn/company/page_%s/
    ctr-project:
      driver-type: chrome
      incognito: false
      open-window: true
      thread-count: 5
      url: https://www.chictr.org.cn/searchproj.html
      max-page: 100
    ctr-project-file:
      driver-type: chrome
      incognito: false
      open-window: true
      thread-count: 5
      save-path: D:\中国临床试验注册中心
    ctr-project-file-parse:
      save-path: :\中国临床试验注册中心
      thread-count: 50
    nmpa-pharmaceutical-company:
      driver-type: firefox
      incognito: false
      open-window: true
      thread-count: 1
      url: https://www.nmpa.gov.cn/datasearch/home-index.html#category=yp
      max-page: 2000
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.onework.boot.scrape.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  application:
    name: onework-scrape
  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:33061/onework_platform?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: ${onework.info.base-package}.*.*.dal.dataobject

